name: Neon and Vercel Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on: [pull_request]
jobs:
  create-branch:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: get_pull_number
        run: |
          pull_sha=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH")
          echo "pull_sha=${pull_sha}" >> $GITHUB_OUTPUT
          echo $pull_sha
      - name: Create Branch
        uses: neondatabase/create-branch-action@v2
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{steps.get_pull_number.outputs.pull_sha}}
          api_key: ${{ secrets.NEON_API_KEY }}
          username: ${{ secrets.PGUSERNAME }}
          password: ${{ secrets.PGPASSWORD }}
        id: create-branch
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Prisma Migrate
        run: |
          touch .env
          echo DATABASE_URL=${DATABASE_URL} >> .env
          echo SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL} >> .env
          npx prisma generate
          npx prisma migrate dev
        env:
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url}}/neondb
          SHADOW_DATABASE_URL: ${{ steps.create-branch.outputs.db_url}}/shadow
      - name: Deploy to Vercel
        id: deploy
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          preview_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "preview_url=${preview_url}" >> $GITHUB_OUTPUT
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Neon Branch Host :elephant: : ${{ steps.create-branch.outputs.host }}
            Vercel Preview URL :rocket: : ${{ steps.deploy.outputs.preview_url }}
